### PR TITLE
Fix errors, args parser

### LINKED ISSUE #2: Exception on startup
```
TypeError: Cannot read property 'getIntegrationApis' of null
    at Timeout.callback [as _onTimeout] (/home/admin/concierge/modules/kpm_say-hi/say-hi.js:15:36)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

`getIntegrationApis` still exists (although can mostly be ignored now that events are in place).

### PR DESCRIPTION
**Pull request by drkno**
resolves #2 by using events instead of polling

### CODE REVIEW

File: say-hi.js [hunk 1]
```diff
@@ -1,111 +1,82 @@
...
-            disableCommand,
-            setCommand
-        ];
-
-exports.load = function () {
-    let search = Object.keys(exports.config);
+const parser = require('concierge/arguments');
+
+const greet = (api, config) => {
+    for (let thread_id of Object.keys(config)) {
```
Comment (fallaciousreasoning) [inline say-hi.js:4]: What does the of keyword do compared to in? Just interested

File: say-hi.js [hunk 2]
```diff
@@ -1,111 +1,82 @@
...
+        const thread = config[thread_id];
+        if (!thread.enabled)
+            continue;
+        const greeting = api.random(thread.greetings || ['Hello World']);
```
Comment (fallaciousreasoning) [inline say-hi.js:8]: What does api.random(undefined) produce? I feel like api.random(thread.greetings) || 'Hello World' would read slightly nicer but I don't really mind either way

Comment (drkno) [reply say-hi.js:8]: I honestly have no idea. I would presume an error, but I can check

**Review by fallaciousreasoning — COMMENTED** [review]
LGTM. Tested?

File: say-hi.js (hunk 2 above)
Comment (fallaciousreasoning) [reply say-hi.js:8]: Nah, no worries

File: say-hi.js (hunk 1 above)
Comment (drkno) [reply say-hi.js:4]:
```js
const foo = ['a', 'b', 'c'];
for (let i of foo) {
   console.log(i);
}
/* out values:
a
b
c
*/

for (let i in foo) {
   console.log(i);
}
/* out keys:
0
1
2
*/
```

The `in` keyword also lets you iterate over non-iterables because it is equivilant to:
```js
for (let i of Object.keys(foo)) {
    // something
}
```

File: say-hi.js (hunk 2 above)
Comment (drkno) [reply say-hi.js:8]: yup, an error

**Comment by drkno** [comment]
Tested working, Concierge 4.1.2
